src/br/ufrn/sigpit/arq/jsf/usuario/CadastrarUsuarioMBean.java
package br.ufrn.sigpit.arq.jsf.usuario;

import java.util.Date;
import java.util.Properties;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Component;

import br.ufrn.sigpit.arq.dao.GenericDao;
import br.ufrn.sigpit.arq.dominio.DadosPessoais;
import br.ufrn.sigpit.arq.jsf.AbstractMBean;
import br.ufrn.sigpit.arq.seguranca.dao.UsuarioDao;
import br.ufrn.sigpit.arq.seguranca.dominio.Usuario;
import br.ufrn.sigpit.arq.service.ServiceCadastro;
import br.ufrn.sigpit.comum.helpers.AutenticacaoHelper;

import javax.mail.Address;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMessage.RecipientType;
import javax.servlet.http.HttpServletRequest;

@ManagedBean
@RequestScoped
@Component
@Scope(value="request")
public class CadastrarUsuarioMBean extends AbstractMBean<Usuario>{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private DadosPessoais dadosp;
	private String senhaConfirm;
	

	public String getSenhaConfirm() {
		return senhaConfirm;
	}

	public void setSenhaConfirm(String senhaConfirm) {
		this.senhaConfirm = senhaConfirm;
	}
	
	@Autowired
	private ServiceCadastro serviceCadastro;
	
	public CadastrarUsuarioMBean(){
		obj = new Usuario();
	}
	
	public String cadastrarDadosAcesso(){
		
		//obj = new Usuario();

		//dadosp = new DadosPessoais(nome, null, sexo);

		obj.setDadosPessoais(dadosp);		
		//obj.setEmail(email);
		//obj.setSenha(AutenticacaoHelper.toMD53(senha));
		//obj.setSenha(senha);
		obj.setChaveConfirmacao(AutenticacaoHelper.gerarChaveConfirmacao());
		
		
		try {
			
			serviceCadastro.salvar(obj);
	        
			sendEmailConfirmation();
	        
	        addFacesInformationMessage("Seu cadastro foi efetuado com sucesso. Ative já sua conta através do email "+obj.getEmail()+".\n  Se o e-mail não estiver em sua caixa de entrada, verifique sua caixa de spam!" );
	        addFacesInformationMessage("Caso não tenha recebido o email de ativação, clique <a href='" + getCurrentRequest().getContextPath() + "/reenviarEmailAtivacao.jsf'>AQUI</a>." );
		}
		catch(DataIntegrityViolationException c){
			c.printStackTrace();
			addGlobalErrorMessage("Já Existe uma conta associada aos seus dados, por favor faça login");
			return "login.jsf";
		} catch (AddressException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return "EmailConfirmacao.jsf";
		
	}
	public void sendEmailConfirmation() throws AddressException, MessagingException{
		  
		  Properties props = new Properties();  
		  props.put("mail.smtp.host","mail.info.ufrn.br");
		  props.put("mail.smtp.port", "25"); 
		 
		  Session session = Session.getDefaultInstance(props);  
		 
		  MimeMessage message = new MimeMessage(session);  	  
		  
		  Address from = new InternetAddress("ticonnectsinfo@gmail.com");  
		  Address to = new InternetAddress(obj.getEmail());  
		   
		  message.setFrom(from);  
		  message.addRecipient(RecipientType.TO, to);  
		  
		  message.setSentDate(new Date());  
		  message.setSubject("Confirmação de Cadastro no SiGPIT");  
		  
		  //Obtendo nome, porta e contexto do servidor
		  String enderecoServidor,porta, contexto;
		  Object request = FacesContext.getCurrentInstance().getExternalContext().getRequest();

		  enderecoServidor = ((HttpServletRequest) request).getLocalName().toString();
		  contexto = ((HttpServletRequest) request).getContextPath().toString();
		  porta = Integer.toString(((HttpServletRequest) request).getServerPort());

		  
		  String html = "<p><h2>Olá "+obj.getNome()+", </h2></p> ";
		  html += "<p><h4>Seja bem-vindo(a) ao SIGS!</h4></p>";
		  html += "<p><h4>Atenção: sua conta encontra-se desativada. Ative já a sua conta clicando <a href='http://"+enderecoServidor+":"+porta+contexto+"/login.jsf?chave="+obj.getChaveConfirmacao()+"'>AQUI</a>.</h4></p>";
		  html += "<p></br><h4>Atenciosamente,</h4></p>";
		  html += "<p><h4>SiGPIT - Sistema de Gerenciamento do Programa de Imerssão Tecnológica</h4></p>";
		  
		  message.setText(html,"ISO-8859-1", "html");  		  
		
		  Transport.send(message);  
		}
	
public String getMensagemConfirmacaoConta() {
		
		String chave = getParameter("chave");
		
//		System.out.println("CadastroMBean.geetMensagemConfirmacaoConta - getParameter" + chave);
		
		if (chave != null){
			UsuarioDao dao = (UsuarioDao) getBean("usuarioDao");
			
			if (dao.isChaveCadastrada(chave)){
				
				obj = dao.findUsuarioByChaveConfirmacao(chave);
				
				if (!obj.isAtivo()){
				
					obj.setAtivo(true);
					
					serviceCadastro.atualizar(obj);
				}
				addFacesInformationMessage("Conta ativada com sucesso! Efetue login no sistema:");
				
				/*
				// A primeira vez que o Gestor ativa precisa redirecionar para um cadastro de empresa 
				for (Permissao p : obj.getPermissoes()) {
					if(p.getPapel().getNome().equals("ROLE_GERENTE")) cadastroGestor = true;
				}
				if(cadastroGestor){
					addFacesInformationMessage("Conta ativada com sucesso! Efetue login no sistema:");
				} else addFacesInformationMessage("Conta ativada com sucesso!");
				
				*/
			} else {
				addGlobalErrorMessage("A conta já foi ativada anteriormente ou o código de acesso não é válido.");
			}
		}
		
		return "";
		
	}
/*
	public String deletarUsuario(){
		System.out.println("Cheguei no deletar e o id: " + obj.getId());
		//deletar(obj.getId());
		return "/login.jsf";	
	}
*/
	public String deletar() {
		//System.out.println("Cheguei no deletar e o id: " + obj.getId());
		GenericDao dao = (GenericDao) getBean("genericDao");
		Usuario user = dao.buscar(Usuario.class, getUsuarioLogado().getId());
		obj = user;
		
		try {
			System.out.println("Cheguei no excluir");
			serviceCadastro.excluir(obj);
		} catch (Exception e) {
			addGlobalErrorMessage("Não foi possível excluir o Usuário.");
		}
		return "/ConfirmExcluirConta.jsf";
	}
}

WebContent/addaluno.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<head>
<meta charset="utf-8"></meta>
<title>SIGS - Sistema Integrado de Gestão de Seleção</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
<meta name="description" content=""></meta>
<meta name="author" content=""></meta>

<!-- Le styles -->
<link
	href="http://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.min.css"
	media="screen, projection" rel="stylesheet" type="text/css" />
<link href="stylesheets/screen.css" media="screen, projection"
	rel="stylesheet" type="text/css" />
<link
	href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css"
	rel="stylesheet"></link>
<link href="./assets/css/bootstrap.css" rel="stylesheet"></link>
<link href="./assets/css/bootstrap-responsive.css" rel="stylesheet"></link>
<link href="./assets/css/style.css" rel="stylesheet"></link>
<style type="text/css">
</style>

<link href="./assets/css/bootstrap-responsive.css" rel="stylesheet"></link>

<link rel="apple-touch-icon-precomposed" sizes="72x72"
	href="./resources/ico.jpg"></link>
<link rel="apple-touch-icon-precomposed" href="./resources/ico.jpg"></link>
<link rel="shortcut icon" href="./resources/ico.jpg"></link>
<style type="text/css">
input,textarea {
	color: #fff;
}

.placeholder {
	color: #fff;
}
</style>
</head>

<h:body>

	<div class="content">

		<div>
			<div class="header">
				<div class="logo">
					<p>SIGPIT</p>
				</div>
				<p>Sistema Integrado de Gestão do programa de imerssão
					tecnologica</p>
				<hr />
				<br />
			</div>
		</div>
	</div>
	<br />
	<div class="logo">
		<p>Turma:</p>
	</div>

	<label class="control-label" for="CodigoTurma">Código da Turma</label>
	<h:outputText id="CodigoTurma" value="#{CadastroBean.idturma}" />
	<br />
	<center>
		<div class="span5">

			<h:form class="form-horizontal">
				
				<h:panelGrid id="gridLoginSenha" columns="2">




					<label class="control-label" for="NomeAluno">Nome do aluno: </label>
					<h:inputText id="NomeAluno" value="#{CadastroBean.nomealuno}" />
					<label class="control-label" for="EmailAluno">Email
						do aluno: </label>
					<h:inputText id="EmailAluno" value="#{CadastroBean.email}" />
					<label class="control-label" for="Area">Área</label>
					<h:selectOneMenu id="Area" value="#{CadastroBean.area}">
						<f:selectItem itemValue="BI" />
						<f:selectItem itemValue="Desenvolvimento" />
						<f:selectItem itemValue="infra-estrutura" />
						<f:selectItem itemValue="Requisitos" />
						<f:selectItem itemValue="Testes" />

					</h:selectOneMenu>
					<label class="control-label" for="Turno">Turno</label>
					<h:selectOneMenu id="Turno" value="#{CadastroBean.turno}">
						<f:selectItem itemValue="Matutino" />
						<f:selectItem itemValue="Vespertino" />
						
					</h:selectOneMenu>

				<h:messages id="erroturma" style="color:red"/>
				</h:panelGrid>
				
				<div class="control-group">
					<div class="controls">
						<h:commandButton action="#{CadastroBean.Cadastro_aluno()}"
							value="Cadastrar" styleClass="btn btn-primary" />
					</div>
				</div>
			</h:form>
		</div>


	</center>
</h:body>
</html>

WebContent/adicionarturma.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<head>
<meta charset="utf-8"></meta>
<title>SIGS - Sistema Integrado de Gestão de Seleção</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
<meta name="description" content=""></meta>
<meta name="author" content=""></meta>

<!-- Le styles -->
<link
	href="http://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.min.css"
	media="screen, projection" rel="stylesheet" type="text/css" />
<link href="stylesheets/screen.css" media="screen, projection"
	rel="stylesheet" type="text/css" />
<link
	href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css"
	rel="stylesheet"></link>
<link href="./assets/css/bootstrap.css" rel="stylesheet"></link>
<link href="./assets/css/bootstrap-responsive.css" rel="stylesheet"></link>
<link href="./assets/css/style.css" rel="stylesheet"></link>
<style type="text/css">
</style>

<link href="./assets/css/bootstrap-responsive.css" rel="stylesheet"></link>

<link rel="apple-touch-icon-precomposed" sizes="72x72"
	href="./resources/ico.jpg"></link>
<link rel="apple-touch-icon-precomposed" href="./resources/ico.jpg"></link>
<link rel="shortcut icon" href="./resources/ico.jpg"></link>
<style type="text/css">
input,textarea {
	color: #fff;
}

.placeholder {
	color: #fff;
}
</style>
</head>

<h:body>

	<div class="content">

		<div>
			<div class="header">
				<div class="logo">
					<p>SIGPIT</p>
				</div>
				<p>Sistema Integrado de Gestão do programa de imerssão
					tecnologica</p>
				<hr />
				<br />
			</div>
		</div>
	</div>
	<br />

	<center>
		<div class="span5">

			<h:form class="form-horizontal">
				<div class="control-group">



					<label class="control-label" for="NomeTurma">Nome da Turma</label>
					
					<h:inputText id="NomeTurma" value="#{CadastroBean.nome}">
						
					</h:inputText>
					<label class="control-label" for="AnoTurma">Ano</label>
					<h:inputText id="AnoTurma" value="#{CadastroBean.ano}" />
					<label class="control-label" for="SemestreTurma">Semestre</label>
					<h:inputText id="SemestreTurma" value="#{CadastroBean.semestre}" />
					<h:messages id="erroturma" style="color:red"/>

				</div>
				<div class="control-group">
					<div class="controls">
						<h:commandButton action="#{CadastroBean.Cadastro()}"
							value="Cadastrar" styleClass="btn btn-primary" />
					</div>
				</div>
			</h:form>
		</div>

 
	</center>
</h:body>
</html>

WebContent/buscarturmas.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">


<head>
<meta charset="utf-8"></meta>
<title>SIGPIT - sistema Integrado de Gestão do programa de imerssão
					tecnologica</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
<meta name="description" content=""></meta>
<meta name="author" content=""></meta>

<!-- Le styles -->
<link
	href="http://netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.min.css"
	media="screen, projection" rel="stylesheet" type="text/css" />
<link href="stylesheets/screen.css" media="screen, projection"
	rel="stylesheet" type="text/css" />
<link
	href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css"
	rel="stylesheet"></link>
<link href="./assets/css/bootstrap.css" rel="stylesheet"></link>
<link href="./assets/css/bootstrap-responsive.css" rel="stylesheet"></link>
<link href="./assets/css/style.css" rel="stylesheet"></link>
<style type="text/css">
</style>

<link href="./assets/css/bootstrap-responsive.css" rel="stylesheet"></link>

<link rel="apple-touch-icon-precomposed" sizes="72x72"
	href="./resources/ico.jpg"></link>
<link rel="apple-touch-icon-precomposed" href="./resources/ico.jpg"></link>
<link rel="shortcut icon" href="./resources/ico.jpg"></link>
<style type="text/css">
input,textarea {
	color: #fff;
}

.placeholder {
	color: #fff;
}
</style>
</head>

<h:body>

	<ul class="nav nav-tabs">
		<li><a href="#">Início</a></li>
		<li class="active"><a href="#">Turmas</a></li>
		<li><a href="#">Atividades</a></li>
		<li><a href="#">Fórum</a></li>
		<li><a href="#">Contéudos</a></li>
		<li><a href="#">Alunos</a></li>
		<li><a href="#">Projetos</a></li>
	</ul>


	<div class="content">

		<div>
			<div class="header">
				<div class="logo">
					<p>SIGPIT</p>
				</div>
				<p>Sistema Integrado de Gestão do programa de imerssão
					tecnologica</p>
				<hr />
				<br />
			</div>
		</div>
	</div>
	<br />



	<h:form>
		<div class="row">
			<div class="col-xs-6 col-sm-6 col-md-6">
				<div class="form-group" style="margin: 0px 0px 0px 25px">
					<h:commandButton action="#{CadastroBean.AddTurmaChamar()}"
						value="Adicionar Turma" styleClass="btn btn-primary" />
					
				</div>

			</div>
		</div>
	</h:form>



	<h:form>
		<h:dataTable value="#{CadastroBean.consultaTurma}" var="item"
			class="table table-striped table-bordered" cellspacing="0"
			width="100%" data-show-refresh="true" data-show-toggle="true"
			data-show-columns="true" data-search="true">

			<h:column>
				<f:facet name="header">
					<h:outputText value="Idturma" />
				</f:facet>
				<div class="control-group">
					<div class="controls">
						<center>
							<h:commandLink action="#{CadastroBean.Turma(item)}"
								value="#{item.idturma}" />
						</center>
					</div>
				</div>
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Nome da Turma" />
				</f:facet>
				<div class="control-group">
					<div class="controls">
						<h:commandLink action="#{CadastroBean.Turma(item)}"
							value="#{item.nome}" />
					</div>
				</div>
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Ano da Turma" />
				</f:facet>
				<div class="control-group">
					<div class="controls">
						<h:commandLink action="#{CadastroBean.Turma(item)}"
							value="#{item.ano}" />
					</div>
				</div>
			</h:column>


			<h:column>
				<f:facet name="header">
					<h:outputText value="Semestre da Turma" />
				</f:facet>
				<div class="control-group">
					<div class="controls">
						<h:commandLink action="#{CadastroBean.Turma(item)}"
							value="#{item.semestre}" />
					</div>
				</div>
			</h:column>
            
            <h:column>
				<f:facet name="header">
					<h:outputText value="Integrantes" />
				</f:facet>
				<div class="control-group">
					<div class="controls">
						<h:commandLink action="#{CadastroBean.Turma(item)}"
							value="#{CadastroBean.numalunos(item)}" />
					</div>
				</div>
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Status" />
				</f:facet>
				<div class="control-group">
					<div class="controls">
						<h:commandLink action="#{CadastroBean.Turma(item)}"
							value="#{item.ativo}" />
					</div>
				</div>
			</h:column>
            
			<h:column>
				<h:commandButton action="#{CadastroBean.Exclusao(item)}"
					value="Delete" styleClass="btn" />
			</h:column>

		</h:dataTable>
	</h:form>


</h:body>
</html>

WebContent/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
<jsp:forward page="buscarturmas.xhtml"></jsp:forward>
</body>
</html>

WebContent/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<head>
<meta charset="utf-8"></meta>
<title>SiGPIT - Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
<meta name="description" content=""></meta>
<meta name="author" content=""></meta>

<!-- Le styles -->
<link href="./assets/css/bootstrap.css" rel="stylesheet"></link>
<link href="./assets/css/bootstrap-responsive.css" rel="stylesheet"></link>
<link href="./assets/css/style.css" rel="stylesheet"></link>
<style type="text/css">
</style>
<link href="./assets/css/bootstrap-responsive.css" rel="stylesheet"></link>

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="./assets/js/html5shiv.js"></script>
    <![endif]-->

<!-- Fav and touch icons -->
<!--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="./resources/ico.jpg"></link>
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="./resources/ico.jpg"></link>
    -->
<link rel="apple-touch-icon-precomposed" sizes="72x72"
	href="#{request.contextPath}/assets/img/ico.jpg"></link>
<link rel="apple-touch-icon-precomposed" href="#{request.contextPath}/assets/img/ico.jpg"></link>
<link rel="shortcut icon" href="#{request.contextPath}/assets/img/ico.jpg"></link>
</head>

<h:body>

	<div class="content">

		<div>
			<div class="header">
				<div class="logo"><p><a href="#{request.contextPath}/pages/index.jsf" style="cursor:pointer">SiGPIT</a></p></div>
				<p>Sistema de Gerenciamento do Programa de Imerssão Tecnológica</p>
				<hr />
				<br />
			</div>
		</div>
		<br />

		<div class="navbar-inner">
			<legend>Login</legend>
			<h:form class="form-horizontal">
				<h:panelGroup endered="#{!requestScope.chave}">
					<h:outputText value="#{cadastroMBean.mensagemConfirmacaoConta}"></h:outputText>
					<h:messages id="msgs2" showDetail="true" escape="false" />
				</h:panelGroup>
				<div class="row-fluid">
					<div class="span5">

						<h:form class="form-horizontal">
							<div class="control-group">
								<label class="control-label" for="inputEmail">Email</label>
								<div class="controls">

									<h:inputText id="inputEmail" value="#{loginMBean.obj.email}"
										label="Email" />
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="inputPassword">Senha</label>
								<div class="controls">
									<h:inputSecret id="inputPassword"
										value="#{loginMBean.obj.senha}" label="Senha" />
								</div>
							</div>
							<div class="control-group">
								<div class="controls">
									<label class="checkbox"> 
										<input type="checkbox">Lembrar</input>
									</label>
									<h:commandButton value="Entrar" styleClass="btn btn-primary"
										action="#{loginMBean.logar}" />
								</div>
							</div>
						</h:form>
					</div>
					
					<!-- <div class="span7">
						<p class="text-center">
							<Strong>Usuário,</Strong><br /> caso ainda não possua cadastro no
							SIGS,<br /> clique no link abaixo.
						</p>
						<p class="text-center">
							<Strong><a href="#{request.contextPath}/cadastrarUsuario.jsf">Cadastre-se</a></Strong>
							<br/><Strong><a href="#{request.contextPath}/reenviarEmailAtivacao.jsf">Reenviar email</a></Strong>
						</p>
					</div>  -->

				</div>


			</h:form>
		</div>


	</div>
	<!-- /container -->

	<!-- Le javascript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="./assets/js/jquery.js"></script>
	<script src="./assets/js/bootstrap-transition.js"></script>
	<script src="./assets/js/bootstrap-alert.js"></script>
	<script src="./assets/js/bootstrap-modal.js"></script>
	<script src="./assets/js/bootstrap-dropdown.js"></script>
	<script src="./assets/js/bootstrap-scrollspy.js"></script>
	<script src="./assets/js/bootstrap-tab.js"></script>
	<script src="./assets/js/bootstrap-tooltip.js"></script>
	<script src="./assets/js/bootstrap-popover.js"></script>
	<script src="./assets/js/bootstrap-button.js"></script>
	<script src="./assets/js/bootstrap-collapse.js"></script>
	<script src="./assets/js/bootstrap-carousel.js"></script>
	<script src="./assets/js/bootstrap-typeahead.js"></script>

</h:body>
</html>